services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    image: cafe-everywhere
    restart: on-failure:5
    ports:
      - 127.0.0.1:8000:8000

networks:
  default:
    name: cafe-everywhere
    external: true
